FROM mcr.microsoft.com/devcontainers/dotnet:8.0

RUN apt update

# install useful tools inside container
RUN apt install -y neovim

# install java
ARG JDK_VERSION=17
RUN apt install -y neovim && \
    apt install -y --no-install-recommends openjdk-${JDK_VERSION}-jdk 
RUN dotnet workload install maui-android
ENV JAVA_HOME /usr/lib/jvm/java-${JDK_VERSION}-openjdk-amd64

# setup android command line tools
ARG ANDROID_SDK_VERSION=11076708
ENV SDK_ROOT=/usr/local/
ENV ANDROID_HOME=${SDK_ROOT}/android-sdk
RUN mkdir -p ${ANDROID_HOME}/cmdline-tools && \
    wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_VERSION}_latest.zip && \
    unzip *tools*linux*.zip -d ${ANDROID_HOME}/cmdline-tools && \
    mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/tools && \
    rm *tools*linux*.zip

# setup build tools 
RUN echo Y | ${ANDROID_HOME}/cmdline-tools/tools/bin/sdkmanager --install "build-tools;34.0.0" "platforms;android-34" "platform-tools"

# update path env
ENV PATH ${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/cmdline-tools/tools/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/emulator

# accept the license agreements of the SDK components
RUN echo Y | ${ANDROID_HOME}/cmdline-tools/tools/bin/sdkmanager --licenses

# connect adb to host
ENV ADB_SERVER_SOCKET=tcp:host.docker.internal:5037